services:
  catalog:
    domain: localhost
    port: 8080
    base-path: /catalog-service/api
  object-store:
    domain: localhost
    port: 8081
    base-path: /object-store/api
  postgres:
    domain: localhost
    port: 5432
    database: catalog
    username: postgres
    password: mysecretpassword
  mongodb:
    host: localhost
    port: 27017
    auto-index-creation: true
